### ISSUE TITLE
导入项目后ftl的标签undefined

### ISSUE THREAD

**Issue by Corpsed** [fanchaoo/hahu#3]
例如：	<#include "nav.html"/>
   提示：Multiple annotations found at this line:
	     - Undefined attribute name (nav.html).
	     - Unknown tag (#include).
	     - Invalid location of text (") in tag 
<#if allQuestion??>
<#else>
类似的全部提示undefined，但是maven已经配置了freemarker的包了==
求解答-使用的是eclipse

**Comment by fanchaoo** [comment]
右键项目，maven update下
要是还不行，就去maven仓库把freemarker的jar包删了，重新下载下

**Comment by Corpsed** [comment]
都试过了--还是提示不行--
